sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

deploy:
  provider: script
  script: bash .travis/docker_push
  on:
    branch: master
   
after_success:
  - sh .travis/deploy_dockerhub.sh