sudo: required

services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=gyllenhammar/cicd-buzz
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO